Repository fga-eps-mds/2024.2-LIVRO-LIVRE-FRONT, pull requests merged in 2025-02, with the labels that each got.

#21 BugFix - US01
  src/pages/SignIn/SignInForm/index.tsx
  src/pages/SignIn/SignUpButton/index.tsx
Labels: HOTFIX

#20 69 qr code
  jest.setup.ts
  package-lock.json
  package.json
  public/botao-voltar.png
  public/boto.jpeg
  public/curupira.jpeg
  public/logo.jpeg
  public/qrcode.jpeg
  src/App.tsx
  src/components/ui/QRcodeReader.tsx
  src/components/ui/rating.tsx
  src/pages/BorrowBook/BorrowBookHeader/index.tsx
  src/pages/BorrowBook/BorrowBookLivro/index.tsx
  src/pages/BorrowBook/BorrowButton/index.tsx
  src/pages/BorrowBook/index.tsx
  src/pages/Home/QRcodeButton/index.tsx
  src/pages/Home/index.tsx
  src/pages/QRcode/QRcodeCamera/index.tsx
  src/pages/QRcode/QRcodeHeader/index.tsx
  src/pages/QRcode/backbutton/index.tsx
  src/pages/QRcode/index.tsx
  src/pages/SignUp/SignUpForm/index.tsx
  test/Home.spec.tsx
  test/QRcodeButton.spec.tsx
  tsconfig.app.json
Labels: US

#27 Us05 homepage
  .env
  jest.setup.ts
  package-lock.json
  package.json
  src/pages/BorrowBook/BackButton/index.tsx
  src/pages/BorrowBook/BorrowButton/index.tsx
  src/pages/BorrowBook/index.tsx
  src/pages/Home/HomeHeader/index.tsx
  src/pages/Home/MostrarLivros/index.tsx
  src/pages/Home/QRcodeButton/index.tsx
  src/pages/Home/index.tsx
  src/pages/QRcode/index.tsx
  test/BorrowBook.spec.tsx
  test/BorrowBookHeader.spec.tsx
  test/BorrowBookLivro.spec.tsx
  test/BorrowButton.spec.tsx
  test/Home.spec.tsx
  test/QRcode.spec.tsx
  test/QRcodeCamera.spec.tsx
  test/QRcodeHeader.spec.tsx
  test/backbutton.spec.tsx
Labels: FIX RELEASE

#26 fixint:all tests
  .env
  jest.setup.ts
  package-lock.json
  package.json
  src/pages/BorrowBook/BorrowButton/index.tsx
  src/pages/QRcode/index.tsx
  test/BorrowBook.spec.tsx
  test/BorrowBookHeader.spec.tsx
  test/BorrowBookLivro.spec.tsx
  test/BorrowButton.spec.tsx
  test/Home.spec.tsx
  test/QRcode.spec.tsx
  test/QRcodeCamera.spec.tsx
  test/QRcodeHeader.spec.tsx
  test/backbutton.spec.tsx
Labels: US
